---
title: "04_celltyping"
format: html
editor: visual
---

## Cell type assignment

```{r}
rm(list = ls())

```

#### Librairy

```{r, massage = False}

library(dplyr)
library(Seurat)
library(patchwork)
library(here)
library(SingleR)
library(celldex)

library(SeuratData)
library(dplyr)
library(tidyr)
library(multtest)
library(metap)
library(tibble)
library(purrr)
```

#### Data Load

```{r, massage = False}

snRNAseq <- readRDS("../data/04_RNA_seurat")

```

Dim plot

```{r}

DimPlot(snRNAseq, reduction = 'umap', group.by = 'RNA_snn_res.0.1')

```

#### Marker genes cell typing

find conserved markger genes acrocces clusters.

```{r}
Idents(snRNAseq) <- "RNA_snn_res.0.1"
DefaultAssay(snRNAseq) <- "RNA"
annotations <- read.csv("/home/projects/22102_single_cell/day3/annotation.csv")
```

```{r}


cluster0_conserved_markers <- FindConservedMarkers(snRNAseq,
                              ident.1 = 0,
                              grouping.var = "condition",
                              only.pos = TRUE,min.pct = 0.25,  min.diff.pct = 0.25,
                      logfc.threshold = 0.25)

#Load the table with gene descriptions to help you identify to what cell types the genes in the cluster can correspond to



# Combine markers with gene descriptions 
cluster0_ann_markers <- cluster0_conserved_markers  |>  
                rownames_to_column(var="gene") |> 
                left_join(y = 
                            unique(
                              annotations[,c("gene_name", "description")]),
                          by = c("gene" = "gene_name"))

cluster0_ann_markers$gene
```

```{r}

snRNAseq <- RenameIdents(object = snRNAseq, 
                                "0" = "epithelial cells",
                                "1" = "CD8+ T cells",
                                "2" = "CD4+ T cells",
                                "3" = "NK cells",
                                "4" = "Monocyte",
                                "5" = "Monocyte",
                                "6" = "T reg",
                                "7" = "DC",
                                "8" = "B cells",
                                "9" = "Unknown",
                                "10" = "Platelet",
                                "11" = "Hematopoietic stem cells",
                                "12" = "Plasma Cells")

# Now, you can view the updated metadata
head(snRNAseq@meta.data)
```

```{r}
# visualize data

snRNAseq$cell_type_1 <- Idents(snRNAseq)

DimPlot(snRNAseq, reduction = 'umap', label = TRUE)
```

#### Singler R cell typing

```{r}

ref <- HumanPrimaryCellAtlasData()
```

```{r}
serat_ref <- readRDS("/home/projects/22102_single_cell/day3/pbmcsca.rds")

```

```{r}
ref <- as.SingleCellExperiment(serat_ref, assay = "RNA")

pbmc_counts <- GetAssayData(snRNAseq, assay = "RNA", layer = 'counts')

pred <- SingleR(test = pbmc_counts,
                ref = ref,
                labels = ref$CellType,
                de.method="wilcox")

snRNAseq$cell_type_2 <- pred$labels[match(rownames(snRNAseq@meta.data), rownames(pred))]
```

```{r}

saveRDS(snRNAseq, file = "../data/05_RNA_seurat")
```

#### 
